import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import QuoteComp from '../components/QuoteComp';
import TimeBlock from '../components/TimeBlock';
import useGetTime from '../hooks/useGetTime';

interface IDate {
  loading: boolean;
  date: {
    hrs: number;
    min: string;
    timezone: any;
    dayOfWeek: number;
    dayOfYear: number;
    weekNumber: number;
    fullTimezone: string;
  };
}

export default function Home() {
  const { date, loading }: IDate = useGetTime();
  const [displayMore, setDisplayMore] = useState(false);
  const [darkMode, setDarkMode] = useState(false);

  // toggel extended display based on button press
  const toggleDisplay = () => {
    setDisplayMore(!displayMore);
  };

  // toggle dark mode based on time of day
  useEffect(() => {
    if (date.hrs < 16 && date.hrs > 5) {
      setDarkMode(false);
    } else {
      setDarkMode(true);
    }
  }, [date]);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='w-full min-h-screen bg-day-mobile dark:bg-night-mobile bg-no-repeat bg-cover'>
        <div className='grid w-full min-h-screen bg-gray-500 bg-opacity-30 pt-8'>
          {!displayMore && <QuoteComp />}
          {!loading ? (
            <TimeBlock
              date={date}
              toggleDisplay={toggleDisplay}
              setDarkMode={setDarkMode}
              displayMore={displayMore}
            />
          ) : (
            <h1>Loading</h1>
          )}
        </div>
      </main>
    </div>
  );
}
