import Head from 'next/head';
import Image from 'next/image';
import { useEffect } from 'react';
import QuoteComp from '../components/QuoteComp';

export default function Home() {
  useEffect(() => {
    fetch('http://worldtimeapi.org/api/ip')
      .then((resp) => resp.json())
      .then((data) => console.log(data))
      .catch((err) => console.error(err));
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full min-h-screen bg-day-mobile bg-no-repeat bg-cover">
        <div className="w-full min-h-screen bg-gray-500 bg-opacity-30 px-6 py-8">
          <QuoteComp />
        </div>
      </main>
    </div>
  );
}
